/** Single source of truth for BO route paths. */
export const ROUTES = {
  login: '/login',
  dashboard: '/dashboard',
  orders: '/orders',
  orderNew: '/orders/new',
  orderDetail: (id = ':id') => `/orders/${id}`,
  products: '/catalog/products',
  productNew: '/catalog/products/new',
  productEdit: (id = ':id') => `/catalog/products/${id}`,
  categories: '/catalog/categories',
  brands: '/catalog/brands',
  branches: '/inventory/branches',
  inventory: '/inventory/stock',
  vouchers: '/vouchers',
  voucherNew: '/vouchers/new',
  voucherEdit: (id = ':id') => `/vouchers/${id}`,
  customers: '/customers',
  customerDetail: (id = ':id') => `/customers/${id}`,
  reviews: '/reviews',
  locations: '/locations',
  roles: '/access/roles',
  roleNew: '/access/roles/new',
  roleDetail: (id = ':id') => `/access/roles/${id}`,
  admins: '/access/admins',
} as const;
